version: "3"
services:
  graphql:
    container_name: graphql
    image: shahcompbio/spectrum-cohort-graphql:latest
    volumes:
      - datavolume:/root/data
  frontend:
    container_name: frontend
    image: shahcompbio/spectrum-cohort-react:latest
    ports:
      - "5001:80"
volumes:
  datavolume:
