version: "3"
services:
  graphql:
    container_name: graphql
    image: shahcompbio/sylph-graphql:latest
    volumes:
      - datavolume:/root/data
  frontend:
    container_name: frontend
    image: shahcompbio/sylph-react:latest
    ports:
      - "5001:80"
    volumes:
      - ./.users:/etc/nginx/.users
volumes:
  datavolume:
